spring:
  application:
    name: eureka-server
server:
  port: 1001

eureka:
  instance:
    #主机名称
    hostname: peer
  client:
    service-url:
      defaultZone: http://172.16.11.81:1001/eureka/,http://172.16.11.81:1002/eureka/,http://172.16.11.81:1003/eureka/




